// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_products_store/test/infrastructure/books/repositories/books_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_products_store/domain/books/datasources/i_books_remote_dao.dart'
    as _i3;
import 'package:flutter_products_store/infrastructure/dtos/book_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBookDto_0 extends _i1.SmartFake implements _i2.BookDto {
  _FakeBookDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IBooksRemoteDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBooksRemoteDao extends _i1.Mock implements _i3.IBooksRemoteDao {
  MockIBooksRemoteDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.BookDto>> list({String? query}) => (super.noSuchMethod(
        Invocation.method(
          #list,
          [],
          {#query: query},
        ),
        returnValue: _i4.Future<List<_i2.BookDto>>.value(<_i2.BookDto>[]),
      ) as _i4.Future<List<_i2.BookDto>>);
  @override
  _i4.Future<_i2.BookDto> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i4.Future<_i2.BookDto>.value(_FakeBookDto_0(
          this,
          Invocation.method(
            #get,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.BookDto>);
}
